language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "JrOo5YmZEG8FHdAbS8ca7jlh2dPGeEAlf6hKur1etPvK0n2+USUYWpaJPL6Be1XgP0ntFBOFpP5J8Yo9bQSKXoPe3leYPS1Z1+ftbYg2L/naLI7mOpKtDplqY2kiM/zjB90OI2bljAomRhdofUAI1op4r9r8hm/xyatnNxGG4APLDAqw8QhClE25d4qLrzAgo6eb5iCap+H1ra8TE1txWNIb9DzB/sa4yhvvOsGr16E4RVGP7O3F3NBZa6nlxyD4d37w8uJxr+UJJjEy27aH2U/tcOEO+6FG27aa/BZESm2h09XTEUkb4iL735KJq2ygJX5Y0SaqGb6417U0VVddUaehH3fulkaZF76E7i9Pr476CWfKZ4NVW+vBfQtJNo9QteyKVPX5b5c/qU0OQdMPjFQ6mE+WiC2ra67GrDag9DUuQZf5NDLbkzP7aCb6ajBuDsIa91bmukjb8qWIpPK8bkMFRfhELoWbPb7Aa2LVicFMbFcDa/ump19HSLOGQXGj6tX7oThafkQgCEkumNx5KhbKVKroOwI/U0XpJqZhjgi3Sm2XTHzY3zgUhiyG4upH7cU0hBeQ23HoNPdSVOXef5M/YJ2ePs5U/cfz5MwXDddAieS0Q35Te9VpE194ahsSKqfSqdlRYMsbgLSE5zyufhniJ4vH379+Krl+2PKP16Y="
